[package]
name = "iconscript"
version = "0.3.0"
edition = "2021"
authors = ["Sergey Vartanov"]
description = "iconscript parser and SVG generator in Rust"
license = "MIT"
repository = "https://github.com/enzet/iconscript"
readme = "README.md"
keywords = ["icons", "svg", "cli"]

[[bin]]
name = "iconscript"
path = "src/main.rs"

[dependencies]
antlr-rust = "0.3.0-beta"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
kurbo = "0.12.0"
lazy_static = "1.4"
linesweeper = "0.1.2"
thiserror = "1.0"
